spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: glen1996
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  main:
    allow-bean-definition-overriding: true