spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: glen1996
    url: jdbc:mysql://localhost:3306/springauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 3000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml, classpath*:/mapper/*Mapper.xml