spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: glen1996
      #driverClassName: oracle.jdbc.driver.OracleDriver
      #url: jdbc:oracle:thin:@localhost:1521:orcl
      driver-class-name: com.mysql.jdbc.Driver
      #serverTimezone=UTC 设置时区
      url: jdbc:mysql://localhost:3306/springauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      #最小连接数
      minIdLe: 5
      #最大连接数
      maxActive: 30
      #解决mysql8小时问题
      validationQuery: SELECT 'X'
      #空闲链接最小空闲时间
      minEvictableIdleTimeMillis: 3000
      #空闲连接检查时间间隔
      timeBetweenEvictionRunsMillis: 6000
      maxWait: 10000
      login:
        password:
        username:
  #ORM映射设置，hibernate需要配置jpa
  jpa:
    hibernate:
      #是否自动建表
      ddl-auto: update
    properties:
      hibernate:
        #是否自动打印hql对应的sql语句
        show-sql: false
        #是否格式化sql语句
        format-sql: false
        #事务交由spring管理
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache:
          use_second_level_cache: false
          use_query_cache: false
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 3000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml, classpath*:/mapper/*Mapper.xml