eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: glen-eureka
  server:
    enable-self-preservation: false
server:
  port: 8081
